name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ECS_CLUSTER: Cn-Demo
  AWS_ECS_SERVICE: new
  DOCKER_IMAGE_TAG: latest 
  AWS_ACCOUNT_ID: 557245836403

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/demo:${{ env.DOCKER_IMAGE_TAG }}

      - name: Update ECS service
        uses: aws-actions/amazon-ecs-deploy@v1
        with:
          cluster: ${{ env.AWS_ECS_CLUSTER }}
          service: ${{ env.AWS_ECS_SERVICE }}
          image: 557245836403.dkr.ecr.eu-central-1.amazonaws.com/demo:latest
